### ISSUE TITLE
Publish full dataset

### ISSUE THREAD

**Issue by zhanggb1997** [whuwuteng/Aerial_Stereo_Dataset#1]
When will the author be able to open all data？

**Comment by whuwuteng** [comment]
Hello, thank you very much for being interested in our work, because the full dataset is too large, we do not have the host to save the full dataset, so we can not put the full dataset online,  if you really want to use the full dataset, we need to find a way to transfer the data to you, but I do not know how to host and transfer the full data(1T). So I suggest that you can use the dataset on [Zenodo](https://zenodo.org/records/10808947) firstly.
